# Generated by Django 3.1.3 on 2023-08-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='person_name',
        ),
    ]
